// Copyright (C) 2026 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Timeline-image integration tests on the SYNTHETIC fixture
// (test/data/timeline_image_synth.json, generated by
// timeline-image-dev/tools/gen-synth-trace.mjs). Unlike the AGPL
// local-only fixtures, this file ships in the repository, so these tests
// run everywhere (upstream CI included) with no skip guard.

import {test, expect} from '@playwright/test';
import {PerfettoTestHelper} from './perfetto_ui_test_helper';

const ANCHOR_WINDOW = {
  // "DrawFrames 1000" spans [1.5s, 1.62s), "DrawFrames 1001" starts at
  // 1.75s — the window covers both anchors.
  start: '1500000000',
  end: '1870000000',
};

interface TestTrace {
  traceInfo?: unknown;
  defaultWorkspace: {tracks: {uri?: string; name?: string; headless?: boolean; children: unknown[]}};
  timelineImage: {
    renderTimelineImage(opts: unknown): Promise<{
      blob: Blob;
      width: number;
      height: number;
      warnings: readonly string[];
      trackBoxes: ReadonlyArray<{
        uri: string;
        name: string;
        top: number;
        height: number;
        depth: number;
      }>;
    }>;
  };
}

test.describe.serial('timeline image (synthetic fixture)', () => {
  test.describe.configure({retries: 2});
  let helper: PerfettoTestHelper;

  test.beforeAll(async ({browser}) => {
    const page = await browser.newPage();
    helper = new PerfettoTestHelper(page);
    await helper.openTraceFile('timeline_image_synth.json');
    await page.waitForFunction(
      () => !!(window as {ctx?: {traceInfo?: unknown}}).ctx?.traceInfo,
      undefined,
      {timeout: 60_000},
    );
  });

  test.afterAll(async () => {
    await helper.page.close();
  });

  test('anchor window renders non-empty with the anchor thread resolvable by name', async () => {
    const result = await helper.page.evaluate(async (win) => {
      const trace = window.ctx as unknown as TestTrace;
      const r = await trace.timelineImage.renderTimelineImage({
        trackNames: [{name: 'RenderThread', tid: 4543}],
        timeSpan: {start: win.start, end: win.end},
        widthPx: 1200,
        devicePixelRatio: 1,
        perTrackTimeoutMs: 20_000,
      });
      const bmp = await createImageBitmap(r.blob);
      const c = document.createElement('canvas');
      c.width = bmp.width;
      c.height = bmp.height;
      const ctx = c.getContext('2d')!;
      ctx.drawImage(bmp, 0, 0);
      const d = ctx.getImageData(260, 0, c.width - 260, c.height).data;
      let nonBg = 0;
      for (let i = 0; i < d.length; i += 40) {
        if (d[i] < 240 || d[i + 1] < 240 || d[i + 2] < 240) nonBg++;
      }
      return {
        warnings: [...r.warnings],
        names: r.trackBoxes.map((b) => b.name),
        nonBg,
      };
    }, ANCHOR_WINDOW);
    expect(result.warnings).toEqual([]);
    expect(result.names.length).toBeGreaterThanOrEqual(1);
    expect(result.names.some((n: string) => n === 'RenderThread 4543')).toBe(true);
    expect(result.nonBg).toBeGreaterThan(50);
  });

  test('default composition contains the scripted tracks in tree order', async () => {
    // On this fixture the interactive tree renders thread groups expanded
    // while the offscreen default collection shows collapsed summary rows,
    // so UI-DOM pairing (G1/G2) is not well-defined here; the structural
    // expectation is asserted directly against the workspace semantics.
    const result = await helper.page.evaluate(async () => {
      const trace = window.ctx as unknown as TestTrace;
      const r = await trace.timelineImage.renderTimelineImage({
        widthPx: 1600,
        devicePixelRatio: 1,
        perTrackTimeoutMs: 30_000,
      });
      return {
        warnings: [...r.warnings],
        boxes: r.trackBoxes.map((b) => ({name: b.name, top: b.top, height: b.height})),
      };
    });
    expect(result.warnings).toEqual([]);
    const names = result.boxes.map((b: {name: string}) => b.name);
    expect(names).toContain('com.example.app 1');
    expect(names).toContain('RenderThread 4543');
    expect(names).toContain('main 100');
    expect(names).toContain('cpu_frequency value');
    // Bands stack top-to-bottom with positive heights.
    let prevTop = -1;
    for (const b of result.boxes) {
      expect(b.height).toBeGreaterThan(0);
      expect(b.top).toBeGreaterThanOrEqual(prevTop);
      prevTop = b.top;
    }
  });

  test('byte determinism on the synthetic fixture', async () => {
    const hashes = await helper.page.evaluate(async (win) => {
      const trace = window.ctx as unknown as TestTrace;
      const opts = {
        trackNames: [{name: 'RenderThread', tid: 4543}],
        timeSpan: {start: win.start, end: win.end},
        widthPx: 1200,
        devicePixelRatio: 1,
        perTrackTimeoutMs: 20_000,
      };
      const render = async () => {
        const r = await trace.timelineImage.renderTimelineImage(opts);
        const u8 = new Uint8Array(await r.blob.arrayBuffer());
        let h = 0x811c9dc5;
        for (const b of u8) h = ((h ^ b) * 0x01000193) >>> 0;
        return h.toString(16);
      };
      return [await render(), await render(), await render()];
    }, ANCHOR_WINDOW);
    expect(hashes[0]).toBe(hashes[1]);
    expect(hashes[0]).toBe(hashes[2]);
  });
});
